version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: chatbot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./API
    container_name: chatbot_api
    restart: always
    env_file:
      - ./API/.env
    environment:
      # This tells the API to connect to the 'redis' service, not 'localhost'
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    volumes:
      - /var/lib/chatbot/chromaDB:/var/lib/chatbot/chromaDB
      - /var/lib/chatbot/chromaDB1:/var/lib/chatbot/chromaDB1
      - /var/lib/chatbot/DB1:/var/lib/chatbot/DB1
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
    container_name: chatbot_frontend
    restart: always
    ports:
      # Map port 3000 on the host to container's port 80 (nginx on host proxies from 80 -> 3000)
      - "3000:80"
    depends_on:
      - api

volumes:
  redis_data:
